db:
    host: 192.168.88.78
    port: "5432"
    user: user
    password: advengauser
    name: astragen
    ssl_mode: disable
spreadsheet_id: 1GAUwJRTtrBT4gr1y3ETsCSlHojrc7VCD2GlGDUM53kQ
update: true
sheets:
    - sheet_name: DI
      signal_type: DI
    - sheet_name: AI
      signal_type: AI
    - sheet_name: DQ
      signal_type: DQ
    - sheet_name: AQ
      signal_type: AQ
function_blocks:
    AI:
        st_template: |-
            (*{{.Comment}}*)
            {{.CdsType}}.{{.Tag}}({{.In.address}} := MODULE_{{.Address}});
        in:
            i_rIn: address
        out: {}
        omx:
            template: ""
            attributes: {}
        opc:
            items: []
    AQ:
        st_template: |-
            (*{{.Comment}}*)
            {{.CdsType}}.{{.Tag}}({{.In.address}} := MODULE_{{.Address}});
        in:
            i_rIn: address
        out: {}
        omx:
            template: ""
            attributes: {}
        opc:
            items: []
    DI:
        st_template: |-
            (*{{.Comment}}*)
            {{.CdsType}}.{{.Tag}}({{.In.address}} := MODULE_{{.Address}});
        in:
            i_xIn: address
        out: {}
        omx:
            template: ""
            attributes: {}
        opc:
            items: []
    DQ:
        st_template: |-
            (*{{.Comment}}*)
            {{.CdsType}}.{{.Tag}}({{.In.address}} := MODULE_{{.Address}});
        in:
            i_xIn: address
        out: {}
        omx:
            template: ""
            attributes: {}
        opc:
            items: []
    MTR:
        st_template: |
            {{.CdsType}}.{{.Tag}}(
            {{- range $lhs, $rhs := .In }}
                {{- if $rhs }}
                  {{ $lhs }} := {{ $rhs }},
                {{- end }}
            {{- end }}
            {{- range $lhs, $rhs := .Out }}
                {{- if $rhs }}
                  {{ $lhs }} => {{ $rhs }}.i_xIn,
                {{- end }}
            {{- end }}
            );
        in:
            i_eOnQuality: work.q_xQuality
            i_rFrequency: spFreq
            i_xFault: failure
            i_xOn: work.q_xValue
        out:
            q_xOffCtl: stop
            q_xOnCtl: start
        omx:
            template: "<object name=\"{{.FB.Tag}}\" \n        base-type=\"unit.Types.{{.FB.CdsType}}.PLC_View\" \n        access-scope=\"global\" \n        aspect=\"unit.PsBase.Aspects.PLC_Aspect\" \n        access-level=\"public\" \n        uuid=\"{{.UUID}}\">\n</object>\n"
            attributes:
                unit.System.Attributes.Description: .FB.Tag
                unit.System.Attributes.TAGNAME: .FB.Equipment
                unit.System.Attributes.Title: .FB.Tag
        opc:
            items:
                - CONFIG.RUNTIME
                - SET_MODE
                - HMI_CMD
                - DIAGN
                - RQST_W
                - CTL_W
                - HMI_BLOCK
                - BLOCK
                - STATE
                - PI.VALUE
                - PI.QUALITY
                - TIMEOUT
                - EXC_ERRORS
    PUMP:
        st_template: |
            {{.CdsType}}.{{.Tag}}(
            {{- range $lhs, $rhs := .In }}
                {{- if $rhs }}
                  {{ $lhs }} := {{ $rhs }},
                {{- end }}
            {{- end }}
            {{- range $lhs, $rhs := .Out }}
                {{- if $rhs }}
                  {{ $lhs }} => {{ $rhs }},
                {{- end }}
            {{- end }}
            );
        in:
            FAULT: pumpFault
            LSO: pumpOn
        out:
            ON_CTL: start
        omx:
            template: "<object name=\"{{.FB.Tag}}\" \n        base-type=\"unit.Types.{{.FB.CdsType}}.PLC_View\" \n        access-scope=\"global\" \n        aspect=\"unit.PsBase.Aspects.PLC_Aspect\" \n        access-level=\"public\" \n        uuid=\"{{.UUID}}\">\n</object>\n"
            attributes:
                unit.System.Attributes.Description: .FB.Tag
                unit.System.Attributes.TAGNAME: .FB.Equipment
                unit.System.Attributes.Title: .FB.Tag
        opc:
            items: []
    VALVE:
        st_template: |
            {{.CdsType}}.{{.Tag}}(
            {{- range $lhs, $rhs := .In }}
                {{- if $rhs }}
                  {{ $lhs }} := {{ $rhs }},
                {{- end }}
            {{- end }}
            {{- range $lhs, $rhs := .Out }}
                {{- if $rhs }}
                  {{ $lhs }} => {{ $rhs }},
                {{- end }}
            {{- end }}
            );
        in:
            LSC: closed
            LSO: opened
        out:
            CLS_CTL: close
            OPN_CTL: open
        omx:
            template: "<object name=\"{{.FB.Tag}}\" \n        base-type=\"unit.Types.{{.FB.CdsType}}.PLC_View\" \n        access-scope=\"global\" \n        aspect=\"unit.PsBase.Aspects.PLC_Aspect\" \n        access-level=\"public\" \n        uuid=\"{{.UUID}}\">\n</object>\n"
            attributes:
                unit.System.Attributes.Description: .FB.Tag
                unit.System.Attributes.TAGNAME: .FB.Equipment
                unit.System.Attributes.Title: .FB.Tag
        opc:
            items:
                - CONFIG.RUNTIME
                - SET_MODE
                - HMI_CMD
                - DIAGN
                - RQST_W
                - CTL_W
                - HMI_BLOCK
                - BLOCK
                - STATE
                - PI.VALUE
                - PI.QUALITY
                - TIMEOUT
                - EXC_ERRORS
    VALVE_D:
        st_template: |
            {{.CdsType}}.{{.Tag}}(
            {{- range $lhs, $rhs := .In }}
                {{- if $rhs }}
                  {{ $lhs }} := {{ $rhs }}.q_xValue,
                {{- end }}
            {{- end }}
            {{- range $lhs, $rhs := .Out }}
                {{- if $rhs }}
                  {{ $lhs }} => {{ $rhs }}.i_xIn,
                {{- end }}
            {{- end }}
            );
        in:
            i_xLSC: closed
            i_xLSO: opened
        out:
            q_xCmdClose: close
            q_xCmdOpen: open
        omx:
            template: "<object name=\"{{.FB.Tag}}\" \n        base-type=\"unit.Types.{{.FB.CdsType}}.PLC_View\" \n        access-scope=\"global\" \n        aspect=\"unit.PsBase.Aspects.PLC_Aspect\" \n        access-level=\"public\" \n        uuid=\"{{.UUID}}\">\n</object>\n"
            attributes:
                unit.System.Attributes.Description: .FB.Tag
                unit.System.Attributes.TAGNAME: .FB.Equipment
                unit.System.Attributes.Title: .FB.Tag
        opc:
            items:
                - CONFIG.RUNTIME
                - SET_MODE
                - HMI_CMD
                - DIAGN
                - RQST_W
                - CTL_W
                - HMI_BLOCK
                - BLOCK
                - STATE
                - PI.VALUE
                - PI.QUALITY
                - TIMEOUT
                - EXC_ERRORS
systems:
    - RSU_7
    - PAZ_7
    - RSU_12
    - PAZ_12
nodesheet: Узлы (копия)
default_opc:
    base_path: '{{.FB.CdsType}}.{{.FB.Tag}}'
    node_prefix: Application.{{.FB.CdsType}}.{{.FB.Tag}}
    namespace: urn:ProsoftSystems:regul_ua_server:iec_data
    nodeIdType: string
    binding: Introduced
productsheet: Изделия
address_template:
    AI: '{{.Product.Tag}}_{{.Module}}.CH{{format_number .Channel 2}}'
    AQ: '{{.Product.Tag}}_{{.Module}}.CH{{format_number .Channel 2}}'
    DI: '{{.Product.Tag}}_{{.Module}}.VALUE.{{decrement .Channel}}'
    DQ: '{{.Product.Tag}}_{{.Module}}.VALUE.{{decrement .Channel}}'
