db:
  host: "192.168.0.119"
  port: "5432"
  user: "user"
  password: "advengauser"
  name: "astragen"
  ssl_mode: "disable"
nodesheet: Узлы (копия)
productsheet: Изделия
spreadsheet_id: "1GAUwJRTtrBT4gr1y3ETsCSlHojrc7VCD2GlGDUM53kQ"
update: true
systems:
  - RSU_7
  - PAZ_7
  - RSU_12
  - PAZ_12
function_blocks:
  MTR:
    in:
      SWON: "pumpOn"
      FAULT: "pumpFault"
    out:
      ON_CTL: "start"
  MTR_ChRP:
    in:
      MTRSWON: "motorOn"
    out:
      ON_CTL_MOTOR: "motorStart"
  VALVE:
    in:
      LSO: "opened"
      LSC: "closed"
    out:
      OPN_CTL: "open"
      CLS_CTL: "close"
